import Foundation

/// A reference to a directory of sprite PNG files following PlayableKit's naming convention.
///
/// Files must be flat (no subdirectories) and named:
///   `idle_00.png`, `idle_01.png`, …
///   `walk_00.png`, `walk_01.png`, …
///   `rolling_00.png`, …
///   `attention_00.png`, …
///   `fainting_00.png`, …
///   `attacking_00.png`, …
///   `wave_00.png`, …
public struct SpriteSet {
    /// Local directory URL containing the sprite PNG files.
    public let directory: URL

    public init(directory: URL) {
        self.directory = directory
    }
}
