import Foundation

/// A reference to a directory of sprite PNG files following PlayableKit's naming convention.
///
/// Files must be flat (no subdirectories) and named:
///   `idle_00.png`, `idle_01.png`, …
///   `walk_00.png`, `walk_01.png`, …
///   `rolling_00.png`, …
///   `attention_00.png`, …
///   `fainting_00.png`, …
///   `attacking_00.png`, …
///   `wave_00.png`, …
public struct SpriteSet {
    /// Local directory URL containing the sprite PNG files.
    public let directory: URL

    public init(directory: URL) {
        self.directory = directory
    }
}

public extension SpriteSet {
    /// A ready-to-use example sprite set: an original, cute pixel-art chameleon that covers every
    /// animation state. Bundled with PlayableKit so you can try the engine without supplying art:
    ///
    /// ```swift
    /// PlayableEngine.shared.start(spriteSet: .exampleChameleon)
    /// ```
    ///
    /// The frames were generated by `Tools/generate_chameleon_sprites.py` in the package repo.
    static var exampleChameleon: SpriteSet {
        guard let url = Bundle.module.url(forResource: "chameleon", withExtension: nil, subdirectory: "Sprites") else {
            fatalError("PlayableKit: bundled 'chameleon' example sprite set is missing from resources.")
        }
        return SpriteSet(directory: url)
    }
}
